apiVersion: apps/v1
kind: Deployment
metadata:
  name: watu-java-api
  labels:
    app: watu-java-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watu-java-api
  template:
    metadata:
      labels:
        app: watu-java-api
    spec:
      imagePullSecrets:
      - name : creddocker
      containers:
        - name: watu-java-api
          image: docker.indianic.com/watu/java-dev-api:<VERSION>
          ports:
            - containerPort: 7300
          imagePullPolicy: Always
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.2.1.1             
---
apiVersion: v1
kind: Service
metadata:
  name: watu-java-api
  labels:
    app: watu-java-api
spec:
  selector:
    app: watu-java-api
  ports:
    - port: 7300
      targetPort: 7300

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: watu-java-api-ingress
spec:
  #tls:
    #- hosts:
      #- test.example.com
      #secretName: nginx-tls-secret
  rules:
  - host: watu-dev-api.devpress.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: watu-java-api
            port:
              number: 7300