package com.peopleapp.enums;

import java.util.HashMap;
import java.util.Map;

public enum MessageCodes {

    CUSTOMISED_MESSAGE("600"),
    INVALID_PROPERTY("601"),
    INTERNAL_SERVER_ERROR("602"),
    INVALID_OPERATION("603"),

    PHONE_NUMBER_ALREADY_VERIFIED("802"),
    PHONE_NUMBER_ALREADY_EXISTS("803"),
    EMAIL_ALREADY_EXISTS("805"),
    INVALID_CONNECTION("807"),
    INVALID_PROFILEID("810"),
    OTP_INVALID("813"),
    INVALID_INITIATE("815"),
    INVALID_CONTACT("817"),
    CONNECTION_REQUEST_ALREADY_SENT_TO_NUMBER("820"),
    ALREADY_CONNECTED("821"),
    INVALID_PENDING_ACTIVITY("826"),
    SOME_ACTIONS_CANNOT_BE_PERFORMED_ON_BLOCKED_USERS("828"),
    CANNOT_PERFORM_ANY_ACTION_WITH_BLOCKED_USERS("829"),
    CANNOT_SEND_CONNECTION_REQUEST_TO_SELF("830"),
    INVITATION_ALREADY_SENT("831"),
    NAME_FIELD_CANNOT_BE_EMPTY("832"),
    INVALID_VERIFICATION_TOKEN("902"),
    INVALID_EMAIL_ADDRESS("905"),
    EXTIS_EMAIL_ADDRESS("906"),
    INVALID_REQUEST("908"),
    UNAUTHORIZED_TO_ACCEPT_IGNORE_REQUESTS("909"),
    INVALID_NETWORK("915"),
    INCOMPLETE_PROFILE_INFORMATION("916"),
    INVALID_NETWORK_MEMBER("917"),
    ACTION_CANNOT_BE_TAKEN("919"),
    REQUEST_NOT_PENDING("920"),
    OWNER_CANNOT_LEAVE_NETWORK("921"),
    PRIVATE_NETWORK_SHARE("922"),
    NEW_OWNER_SAME_AS_PREVIOUS("923"),
    NETWORK_NAME_ALREADY_EXIST("924"),
    NETWORK_MEMBER_ALREADY_EXIST("925"),
    NETWORK_REQUEST_ALREADY_SENT("926"),
    INVALID_NETWORK_CATEGORY("927"),
    OWNER_CANNOT_BE_DEMOTED("928"),
    NETWORK_OWNER_CANNOT_DELETE_ACCOUNT("929"),
    NETWORK_EDIT_NAME_ALREADY_EXIST("930"),
    NETWORK_INVITEE_SENT("931"),
    NETWORK_SHARED("932"),
    NETWORK_SHARED_CONTACTS_CANNOT_BE_REMOVED("933"),
    NETWORK_JOIN_REQUEST_CANNOT_BE_SENT_TO_PRIVATE_NETWORK("934"),


    INVALID_USER_GROUP("1000"),
    GROUP_NAME_ALREADY_EXISTS("1001"),
    INVALID_ACTIVITY("1002"),
    REFERRAL_ALREADY_SENT("1003"),
    CANNOT_ACCEPT_BLOCKED_USER_CONNECTION_REQUEST("1004"),
    SEARCHED_OWN_CONTACT_NO("1005"),
    CUSTOM_PRIVACY_PROFILE_NAME_ALREADY_EXISTS("1006"),
    INVALID_COUNTRY_CODE_OR_PHONE_NUMBER("1007"),
    DEFAULT_PRIVACY_PROFILE_CANNOT_BE_DELETED("1008"),
	PUBLIC_PRIVACY_PROFILE_CANNOT_BE_DELETED("1009");


    private static final Map<String, MessageCodes> MESSAGE_CODE_MAP = new HashMap<>();

    static {
        for (MessageCodes myEnum : values()) {
            MESSAGE_CODE_MAP.put(myEnum.getValue(), myEnum);
        }
    }

    private String value;

    private MessageCodes(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static MessageCodes getByValue(String value) {
        return MESSAGE_CODE_MAP.get(value);
    }

}
